#!/bin/bash
rm -f ./version/version.h

VER=`git rev-list origin/master | wc -l | awk '{print $1}'`

if [ $VER -ge 1 ] ; then
    VER="V${VER}_$(git rev-list HEAD -n 1 | cut -c 1-7)"
else
    VER="XXX"
fi

echo "#ifndef VERSION_H
#define VERSION_H
#define VERSION_NUMBER \"$VER\"
#endif // VERSION_H" > ./version/version.h
