/******************************************************************
** 文件名:	error_code.h
** Copyright (c) 2012-2014 *********公司技术开发部
** 创建人:	wguilin
** 日　期:	2012.03
** 修改人:
** 日　期:
** 描　述:	16  进制打印
** ERROR_CODE:
**
** 版　本:	V1.0
*******************************************************************/

#ifndef __ERROR_CODE__
#define __ERROR_CODE__
#include "base_type.h"


#define SUCCESS 				0X00
#define FAIL	 				0X01
#define ERRORS 				0XFF
#define Open_FAIL 				0XFE
#define TIME_OUT 				0XFD
#define Update_Pend				0XFC
#define Pointer_Err				0xFB
#define Pointer_NULL				0xFA
#define NO_SUCH_SUBCMD 			0xFFF0


#define ETHER_LINE_DISCNT_ERR 		0xE001
#define SOCKET_CREAT_FAIL_ERR 		0xE002
#define LINK_TEST_FAIL_ERR	    		0xE003
#define FAAL_MAKEPACK_ERR 	    	0xE004
#define ETHER_RAWSOCK_ERR       		0xE005
#define ETHER_RAWSEND_ERR	    	0xE006
#define ETHER_RAWIOCTL_ERR	    	0xE007
#define FAAL_PACKAGE_CHK_ERR  		0xE008
#define FAAL_PACKAGE_TAIL_ERR  		0xE009
#define ETHER_RAWTIMEOUT_ERR  		0xE00A
#define ETHER_SOCK_ERR		     	0xE00B		//57355
#define ETHER_RECV_LEN_ERR		0xE00C
#define ETHER_CONNECT_CORRUPT_ERR	0xE00D
#define ETHER_SOCK_CREATE_ERR		0xE00E
#define ETHER_SOCK_SETOPT_ERR		0xE00F
#define ETHER_SOCK_CONNECT_ERR	0xE010
#define HOST_NAME_UNAVAILABLE_ERR	0xE011
#define ETHER_LOGON_ERR			0xE012
#define ETHER_SOCKET_DISCNECT_ERR	0xE013

#define SOCKET_CONNECT_ERR		0xE020		//57376
#define CC_LOGON_ERR			0xE021
#define CC_LINKTEST_ERR			0xE022
#define CC_KEEPALIVE_ERR			0xE023		//57379
#define CC_XXXXX_ERR			0xE024
#define CC_SERVER_REFUSE_LOGON_ERR	0xE025
#define CC_SERVER_REFUSE_ACKHEARTBEAT_ERR	0xE026
#define TASK_QUEUE_INIT_ERR		0xE030
#define TASK_NOZONE_EXIST_ERR		0xE031		//57376
#define TASK_NOCMD_EXIST_ERR		0xE032		//57376
#define TASK_QUEUE_APPEND_ERR		0xE033
#define TASK_QUEUE_EMPTY 			0xE035
#define TASK_QUEUE_NO_NODE		0xE038
#define TASK_QUEUE_NO_TIMERTASK_DATFILE  	0xE036
#define TASK_QUEUE_NOSUCH_QUEUE_ERR	0xE037

#define PLC_QUEFULLOR_DEVICBUSY 		0xE033
#define GPRS_QUEFULLOR_DEVICBUSY	0xE034
#define CC_QUEFULLOR_DEVICBUSY   		0xE035
#define D485_QUEFULLOR_DEVICBUSY 	0xE036
#define ETH_QUEFULLOR_DEVICBUSY 		0xE037
#define RTC_DEV_OPEN_ERR			0xE038
#define RTC_DEV_IOCTL_ERR			0xE038
#define UARTPORT_NON_EXIST_ERR		0xE100
#define UARTPORT_OPEN_ERR		0xE101
#define UARTPORT_NO_OPEN			0xE102
#define UARTPORT_SPEED_SET_ERR		0XE103
#define UARTPORT_GETATTR_ERR		0xE104
#define UARTPORT_SETATTR_ERR		0xE105
#define UARTPORT_SEND_ERR			0xE106
#define UART_BUF_CLEAR_ERR		0xE107
#define DATABASE_CREAT_ERR		0xE201
#define DATABASE_OPEN_ERR			0xE202
#define DATABASE_XXXX_ERR			0xE203
#define BURGLALARMTABLE_ELEM_DEL_ERR	0xE301
#define BURGLALARMTABLE_ELEM_INSERT_ERR	0xE302
#define BURGLALARMTABLE_ELEM_UNION_ERR	0xE303
#define BURGLALARMTABLE_ELEM_UPDATE_ERR	0xE304
#define PARAM_SQLITE_LOAD_ERR		0xE401
#define PARAM_FILE_LOAD_ERR		0xE501
#define PARAM_FILE_FIND_ERR		0xE502
#define PARAM_FILE_NOT_EXIST		0xE503
#define TIMER_TASK_INSERT_ERR		0xE601
#define TIMER_TASK_TIMERSET_ERR		0xE602
#define TASK_ELSEMODESET_ERR		0xE603
#define DIDO_OPENINF_SBACK_ERR		0xE701
#define DIDO_OPRATE_ERR			0xE702
#define DIDO_QUERY_ERR			0xE703
#define DIDO_INPUT_QUERY_ERR		0xE704
#define DIDO_SERIAL_OUTOFRANGE_ERR	0xE705
#define METER_REALTIME_READ_ERR 		0XE801
#define CMD_RESET_ACTION_ERR 		0XE901

/*function*/
SINT debug_err_reccord(UINT value);

#endif
